# Generated by Django 3.2.5 on 2021-08-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web2', '0002_alter_host_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
