# Generated by Django 3.2.5 on 2021-08-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='depart',
            table='depart',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
